# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

"""
TT hardware sanity tests for masked_scatter_ decompositions in DeepSeek OCR.

Adds the v2 decomposition (mul+add index linearization) alongside the
original variants. The v2 decomp replaces torch.gather with explicit
    flat_idx = source_idx * D + col_arange
to avoid the ttnn.matmul precision bug on Wormhole (tt-metal#42845).

Context:
  - Issue #3316: masked_scatter_ fails with dynamic shapes on TT.
  - Issue #3412: old decomp runs cumsum on [S*D] int64 -> OOM on TT.
  - Issue #4328: torch.gather in new decomp causes PCC drop via matmul bug.
  - V2 decomp: mul+add bypasses matmul entirely, expected PCC ~1.0 on TT.

Usage:
  pytest tests/torch/models/deepseek_ocr_2/test_masked_scatter_decomp_tt.py -svv
"""

import pytest
import torch
import torch.nn as nn
from infra import Framework, run_op_test
from tests.infra.evaluators.evaluation_config import ComparisonConfig, PccConfig


S = 913
D = 1280
NUM_TRUE = 903


def _build_inputs(S, D, num_true, seed=42):
    torch.manual_seed(seed)
    inputs_embeds = torch.randn(S, D, dtype=torch.bfloat16)
    source = torch.randn(num_true, D, dtype=torch.bfloat16)

    mask_1d = torch.zeros(S, dtype=torch.bool)
    true_positions = torch.randperm(S)[:num_true].sort().values
    mask_1d[true_positions] = True
    return inputs_embeds, mask_1d, source


# ---------------------------------------------------------------------------
# nn.Module wrappers for run_op_test
# ---------------------------------------------------------------------------
class MaskedScatterReference(nn.Module):
    """Wraps torch.Tensor.masked_scatter_ as an nn.Module."""

    def forward(self, inputs_embeds, mask_1d, source):
        result = inputs_embeds.clone()
        result.masked_scatter_(mask_1d.unsqueeze(-1), source)
        return result


class MaskedScatterOldDecomp(nn.Module):
    """Old decomposition: flatten to 1D, cumsum on [S*D] elements."""

    def forward(self, inputs_embeds, mask_1d, source):
        mask = mask_1d.unsqueeze(-1)
        mask_broad, data = torch.broadcast_tensors(mask, inputs_embeds)
        mask_flat = mask_broad.reshape(-1)
        data_flat = data.reshape(-1)
        source_flat = source.reshape(-1)
        mask_i = mask_flat.long()
        source_idx = torch.cumsum(mask_i, 0) - 1
        source_idx = torch.clamp(source_idx, 0, source_flat.shape[0] - 1)
        gathered = source_flat[source_idx]
        result_flat = torch.where(mask_flat, gathered, data_flat)
        return result_flat.view_as(inputs_embeds)


class MaskedScatterNewDecomp(nn.Module):
    """New decomposition: row-level cumsum on [S], 2D gather."""

    def forward(self, inputs_embeds, mask_1d, source):
        mask_i = mask_1d.long()
        source_idx = torch.cumsum(mask_i, 0) - 1
        source_idx = torch.clamp(source_idx, 0, source.shape[0] - 1)
        source_idx_2d = source_idx.unsqueeze(-1).expand_as(inputs_embeds)
        gathered_rows = torch.gather(source, 0, source_idx_2d)
        return torch.where(mask_1d.unsqueeze(-1), gathered_rows, inputs_embeds)


class MaskedScatterNewDecompV2(nn.Module):
    """New decomposition v2: row-level cumsum + mul+add index linearization.

    Replaces torch.gather with:
        flat_idx = source_idx * D + col_arange
        gathered = flat_source[flat_idx]
    This avoids the ttnn.matmul generated by XLA for torch.gather's index
    linearization, bypassing the Wormhole hardware precision bug (#38306).
    """

    def forward(self, inputs_embeds, mask_1d, source):
        S, D = inputs_embeds.shape
        mask_i = mask_1d.long()
        source_idx = torch.cumsum(mask_i, 0) - 1
        source_idx = torch.clamp(source_idx, 0, source.shape[0] - 1)
        flat_source = source.reshape(-1)
        col_idx = torch.arange(D, device=source.device, dtype=source_idx.dtype)
        flat_idx = source_idx.unsqueeze(-1) * D + col_idx.unsqueeze(0)
        gathered_rows = flat_source[flat_idx.reshape(-1)].reshape(S, D)
        return torch.where(mask_1d.unsqueeze(-1), gathered_rows, inputs_embeds)


class MaskedScatterNewDecompV2CompilerDisabled(nn.Module):
    """V2 decomposition with @torch.compiler.disable.

    Runs eagerly on CPU (excluded from XLA tracing) as a control test.
    Should produce PCC ~1.0 since logic never touches TT device.
    """

    @torch.compiler.disable
    def forward(self, inputs_embeds, mask_1d, source):
        S, D = inputs_embeds.shape
        mask_i = mask_1d.long()
        source_idx = torch.cumsum(mask_i, 0) - 1
        source_idx = torch.clamp(source_idx, 0, source.shape[0] - 1)
        flat_source = source.reshape(-1)
        col_idx = torch.arange(D, device=source.device, dtype=source_idx.dtype)
        flat_idx = source_idx.unsqueeze(-1) * D + col_idx.unsqueeze(0)
        gathered_rows = flat_source[flat_idx.reshape(-1)].reshape(S, D)
        return torch.where(mask_1d.unsqueeze(-1), gathered_rows, inputs_embeds)


class MaskedScatterNewDecompCompilerDisabled(nn.Module):
    """New decomposition (gather-based) with torch.compiler.disable."""

    @torch.compiler.disable
    def forward(self, inputs_embeds, mask_1d, source):
        mask_i = mask_1d.long()
        source_idx = torch.cumsum(mask_i, 0) - 1
        source_idx = torch.clamp(source_idx, 0, source.shape[0] - 1)
        source_idx_2d = source_idx.unsqueeze(-1).expand_as(inputs_embeds)
        gathered_rows = torch.gather(source, 0, source_idx_2d)
        return torch.where(mask_1d.unsqueeze(-1), gathered_rows, inputs_embeds)


class MaskedScatterOldDecompCompilerDisabled(nn.Module):
    """Old decomposition with torch.compiler.disable on forward."""

    @torch.compiler.disable
    def forward(self, inputs_embeds, mask_1d, source):
        mask = mask_1d.unsqueeze(-1)
        mask_broad, data = torch.broadcast_tensors(mask, inputs_embeds)
        mask_flat = mask_broad.reshape(-1)
        data_flat = data.reshape(-1)
        source_flat = source.reshape(-1)
        mask_i = mask_flat.long()
        source_idx = torch.cumsum(mask_i, 0) - 1
        source_idx = torch.clamp(source_idx, 0, source_flat.shape[0] - 1)
        gathered = source_flat[source_idx]
        result_flat = torch.where(mask_flat, gathered, data_flat)
        return result_flat.view_as(inputs_embeds)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture
def model_inputs():
    inputs_embeds, mask_1d, source = _build_inputs(S, D, NUM_TRUE)
    return [inputs_embeds, mask_1d, source]


@pytest.fixture
def comparison_config():
    return ComparisonConfig(
        pcc=PccConfig(required_pcc=0.99),
    )


# ---------------------------------------------------------------------------
# 1. masked_scatter_ reference — crashes on TT (repeat_interleave/transpose)
# ---------------------------------------------------------------------------
@pytest.mark.single_device
def test_masked_scatter_reference_tt(model_inputs, comparison_config):
    """masked_scatter_ on TT device. Crashes with TT_FATAL."""
    model = MaskedScatterReference()
    model.eval()

    run_op_test(
        model,
        model_inputs,
        comparison_config=comparison_config,
        framework=Framework.TORCH,
    )


# ---------------------------------------------------------------------------
# 2. New decomposition (gather-based) — PCC drop from matmul bug
# ---------------------------------------------------------------------------
@pytest.mark.single_device
def test_masked_scatter_new_decomp_tt(model_inputs, comparison_config):
    """
    New decomposition (row-level cumsum + 2D gather) on TT device.
    PCC drops due to ttnn.matmul precision bug in gather decomposition.
    """
    model = MaskedScatterNewDecomp()
    model.eval()

    run_op_test(
        model,
        model_inputs,
        comparison_config=comparison_config,
        framework=Framework.TORCH,
    )


# ---------------------------------------------------------------------------
# 3. V2 decomposition (mul+add) — expected to PASS with PCC ~1.0
# ---------------------------------------------------------------------------
@pytest.mark.single_device
def test_masked_scatter_new_decomp_v2_tt(model_inputs, comparison_config):
    """
    V2 decomposition (row-level cumsum + mul+add index linearization).
    Bypasses ttnn.matmul entirely — expected PCC ~1.0 on TT device.
    """
    model = MaskedScatterNewDecompV2()
    model.eval()

    run_op_test(
        model,
        model_inputs,
        comparison_config=comparison_config,
        framework=Framework.TORCH,
    )


# ---------------------------------------------------------------------------
# 4. Old decomposition — crashes on TT (repeat_interleave)
# ---------------------------------------------------------------------------
@pytest.mark.single_device
def test_masked_scatter_old_decomp_tt(model_inputs, comparison_config):
    """Old decomposition on TT device. Crashes with TT_FATAL."""
    model = MaskedScatterOldDecomp()
    model.eval()

    run_op_test(
        model,
        model_inputs,
        comparison_config=comparison_config,
        framework=Framework.TORCH,
    )


# ---------------------------------------------------------------------------
# 5. V2 decomposition with compiler disabled (control)
# ---------------------------------------------------------------------------
@pytest.mark.single_device
def test_masked_scatter_new_decomp_v2_compiler_disabled_tt(
    model_inputs, comparison_config
):
    """
    V2 decomposition with @torch.compiler.disable.
    Runs eagerly on CPU — control test, should produce PCC ~1.0.
    """
    model = MaskedScatterNewDecompV2CompilerDisabled()
    model.eval()

    run_op_test(
        model,
        model_inputs,
        comparison_config=comparison_config,
        framework=Framework.TORCH,
    )


# ---------------------------------------------------------------------------
# 6. New decomposition (gather) with compiler disabled
# ---------------------------------------------------------------------------
@pytest.mark.single_device
def test_masked_scatter_new_decomp_compiler_disabled_tt(
    model_inputs, comparison_config
):
    """New decomposition (gather-based) with @torch.compiler.disable."""
    model = MaskedScatterNewDecompCompilerDisabled()
    model.eval()

    run_op_test(
        model,
        model_inputs,
        comparison_config=comparison_config,
        framework=Framework.TORCH,
    )


# ---------------------------------------------------------------------------
# 7. Old decomposition with compiler disabled
# ---------------------------------------------------------------------------
@pytest.mark.single_device
def test_masked_scatter_old_decomp_compiler_disabled_tt(
    model_inputs, comparison_config
):
    """Old decomposition with @torch.compiler.disable."""
    model = MaskedScatterOldDecompCompilerDisabled()
    model.eval()

    run_op_test(
        model,
        model_inputs,
        comparison_config=comparison_config,
        framework=Framework.TORCH,
    )
