# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by scripts/gen_mlir_files_list.py — do not edit by hand.
# Re-run the script to regenerate this file.

MLIR_FILES = [
    (
        "stablehlo",
        "modules/irs/shlo_compiler_llama_3_2_1b_bs32_isl128_runa0f0_g0_1772724204737.mlir",
    ),
    (
        "stablehlo",
        "modules/irs/shlo_compiler_llama_3_2_1b_bs32_isl128_runa0f0_g1_1772724317290.mlir",
    ),
    ("ttir", "modules/irs/ttir_llama_3_2_1b_bs32_isl128_runa0f0_g0_1772724204912.mlir"),
    ("ttir", "modules/irs/ttir_llama_3_2_1b_bs32_isl128_runa0f0_g1_1772724317413.mlir"),
    ("ttnn", "modules/irs/ttnn_llama_3_2_1b_bs32_isl128_runa0f0_g0_1772724234069.mlir"),
    ("ttnn", "modules/irs/ttnn_llama_3_2_1b_bs32_isl128_runa0f0_g1_1772724323642.mlir"),
]
