# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by scripts/gen_mlir_files_list.py — do not edit by hand.
# Re-run the script to regenerate this file.

MLIR_FILES = []
