# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
"""
Parse the ops_perf_results CSV generated by `python -m tracy -r` and
print a table sorted by total device kernel time, plus a Markdown summary.

Usage:
    python analyze_profile.py <path-to-ops_perf_results*.csv>
    python analyze_profile.py --dir <profiler-output-dir>
"""

import argparse
import glob
import os
import sys

import pandas as pd


def find_csv(directory):
    pattern = os.path.join(directory, "**", "ops_perf_results*.csv")
    matches = sorted(glob.glob(pattern, recursive=True))
    if not matches:
        raise FileNotFoundError(f"No ops_perf_results*.csv found under {directory}")
    return matches[-1]   # most recent


def load_and_clean(path):
    df = pd.read_csv(path, low_memory=False)
    df.columns = [c.strip() for c in df.columns]

    # Coerce timing columns to numeric
    time_cols = [c for c in df.columns if "[ns]" in c or "DURATION" in c.upper()]
    for c in time_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    return df


def summarize_by_op(df):
    """Aggregate per op-code: total calls, total device kernel time, avg."""
    device_col = "DEVICE KERNEL DURATION [ns]"
    host_col   = "HOST DURATION [ns]"

    has_device = device_col in df.columns
    has_host   = host_col in df.columns

    if not has_device and not has_host:
        raise ValueError(f"Neither '{device_col}' nor '{host_col}' found in CSV.\nColumns: {df.columns.tolist()}")

    time_col = device_col if has_device else host_col
    unit_label = "Device kernel" if has_device else "Host"

    agg = (
        df.groupby("OP CODE")
        .agg(
            calls=(time_col, "count"),
            total_ns=(time_col, "sum"),
            avg_ns=(time_col, "mean"),
            min_ns=(time_col, "min"),
            max_ns=(time_col, "max"),
        )
        .reset_index()
        .sort_values("total_ns", ascending=False)
    )

    total_all_ns = agg["total_ns"].sum()
    agg["pct"] = 100.0 * agg["total_ns"] / total_all_ns if total_all_ns > 0 else 0.0
    agg["cumulative_pct"] = agg["pct"].cumsum()

    return agg, time_col, unit_label, total_all_ns


def print_table(agg, unit_label, total_all_ns, top_n=40):
    us = 1e3   # ns → µs

    print(f"\n{'='*110}")
    print(f"  Op breakdown sorted by total {unit_label} time  "
          f"(grand total: {total_all_ns/1e6:.1f} ms)")
    print(f"{'='*110}")
    hdr = (f"  {'OP CODE':<45} {'calls':>6} {'total ms':>10} {'avg µs':>10} "
           f"{'min µs':>9} {'max µs':>9} {'%':>6} {'cum%':>7}")
    print(hdr)
    print("-"*110)
    for _, row in agg.head(top_n).iterrows():
        print(
            f"  {row['OP CODE']:<45} {int(row['calls']):>6} "
            f"{row['total_ns']/1e6:>10.2f} "
            f"{row['avg_ns']/us:>10.1f} "
            f"{row['min_ns']/us:>9.1f} "
            f"{row['max_ns']/us:>9.1f} "
            f"{row['pct']:>6.2f} "
            f"{row['cumulative_pct']:>7.1f}"
        )
    if len(agg) > top_n:
        rest = agg.iloc[top_n:]
        print(f"  {'... ({} more ops)'.format(len(rest)):<45} "
              f"{rest['calls'].sum():>6} "
              f"{rest['total_ns'].sum()/1e6:>10.2f}")
    print("="*110)


def write_markdown(agg, unit_label, total_all_ns, out_path, top_n=40):
    lines = [
        f"# Op Timing Breakdown — {unit_label} time",
        f"",
        f"Grand total: **{total_all_ns/1e6:.1f} ms**",
        f"",
        f"| # | OP CODE | calls | total ms | avg µs | min µs | max µs | % | cum% |",
        f"|---|---------|------:|---------:|-------:|-------:|-------:|--:|-----:|",
    ]
    us = 1e3
    for i, (_, row) in enumerate(agg.head(top_n).iterrows(), 1):
        lines.append(
            f"| {i} | `{row['OP CODE']}` | {int(row['calls'])} "
            f"| {row['total_ns']/1e6:.2f} "
            f"| {row['avg_ns']/us:.1f} "
            f"| {row['min_ns']/us:.1f} "
            f"| {row['max_ns']/us:.1f} "
            f"| {row['pct']:.2f} "
            f"| {row['cumulative_pct']:.1f} |"
        )
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nMarkdown table written → {out_path}")


def main():
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("csv", nargs="?", help="Direct path to ops_perf_results CSV")
    group.add_argument("--dir", help="Search directory for ops_perf_results CSV")
    parser.add_argument("--top", type=int, default=40, help="How many ops to show (default 40)")
    parser.add_argument("--out", default=None, help="Path to write Markdown summary")
    args = parser.parse_args()

    csv_path = args.csv if args.csv else find_csv(args.dir)
    print(f"Reading: {csv_path}")

    df = load_and_clean(csv_path)
    print(f"  {len(df)} rows, {len(df['OP CODE'].unique())} unique op codes")

    agg, time_col, unit_label, total_ns = summarize_by_op(df)
    print_table(agg, unit_label, total_ns, top_n=args.top)

    out_md = args.out or os.path.join(os.path.dirname(csv_path), "op_timing_breakdown.md")
    write_markdown(agg, unit_label, total_ns, out_md, top_n=args.top)


if __name__ == "__main__":
    main()
