name: Bug report
description: File a bug or issue 
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        :star2: Thanks for taking the time to report this issue! :star2:

  - type: textarea
    id: describe-bug
    attributes:
       label: Describe the bug
       description: |
         A clear and concise description of what the bug is and how to reproduce it.

  - type: textarea
    id: reproduce-bug
    attributes:
       label: Steps to reproduce the behavior
       description: |
         When possible/applicable, include the commands that you ran.
       value: |
         1. Go to '...'
         2. Click on '....'
         3. Scroll down to '....'
         4. See error

  - type: textarea
    id: behavior
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to explain your problem.

  - type: textarea
    id: environment-info
    attributes:
      label: Please complete the following environment information
      value:
        - OS`:` (e.g. Ubuntu 22.04)
        - Python version
        - Version of software (e.g. release wheel or commit ID if you built from source)

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.