# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by tests/integrations/tt_mlir_builder/run_test_op_by_op.py — do not edit by hand.
# Re-run the script to regenerate this file.

MLIR_FILES = [
    (
        "stablehlo",
        "modules/irs/shlo_compiler_llama_3_2_1b_bs32_isl128_run4e4d_g0_1772739553012.mlir",
    ),
    (
        "stablehlo",
        "modules/irs/shlo_compiler_llama_3_2_1b_bs32_isl128_run4e4d_g1_1772739607731.mlir",
    ),
    ("ttir", "modules/irs/ttir_llama_3_2_1b_bs32_isl128_run4e4d_g0_1772739553198.mlir"),
    ("ttir", "modules/irs/ttir_llama_3_2_1b_bs32_isl128_run4e4d_g1_1772739607855.mlir"),
    ("ttnn", "modules/irs/ttnn_llama_3_2_1b_bs32_isl128_run4e4d_g0_1772739582600.mlir"),
    ("ttnn", "modules/irs/ttnn_llama_3_2_1b_bs32_isl128_run4e4d_g1_1772739614030.mlir"),
]
