# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by tests/integrations/tt_mlir_builder/run_test_op_by_op.py — do not edit by hand.
# Re-run the script to regenerate this file.

MLIR_FILES = []
