#!/bin/bash

if [ -z "$TT_XLA_ROOT" ]; then
  echo "ERROR: TT_XLA_ROOT not set. Abort"
  exit 1
fi

export XDG_CACHE_HOME="$PWD/.cache"
export TT_METAL_CACHE="$PWD/.cache"
export TTMLIR_VENV_DIR=$PWD/.local_venv
export TT_RANDOM_WEIGHTS=1

cd $TT_XLA_ROOT
source venv/activate
cd -
