name: "Build tt-xla"
description: "Composite action for building, testing, and uploading artifacts for tt-xla."
inputs:
  build-output-dir:
    description: "Build folder location"
    required: true
  install-output-dir:
    description: "Install folder location"
    required: true
  work-dir:
    description: "tt-xla root"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: bash
      run: |
        source venv/activate
        cmake -G Ninja \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DCODE_COVERAGE=ON \
        -B ${{ inputs.build-output-dir }} \
        -S ${{ inputs.work-dir }}

    - name: Build
      shell: bash
      run: |
        source venv/activate
        cmake --build ${{ inputs.build-output-dir }}
        cmake --install ${{ inputs.build-output-dir }}

    # - name: Build the wheel
    #   shell: bash
    #   run: |
    #     source venv/activate
    #     cd ${{ inputs.work-dir }}/python_packages/pjrt_plugin_tt
    #     python setup.py bdist_wheel

    # - name: Upload tt xla wheel
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: xla-wheel
    #     path: ${{ inputs.work-dir }}/python_packages/pjrt_plugin_tt/jax_plugins/pjrt_plugin_tt/dist/pjrt_plugin_tt*.whl

    # - name: Archive Install Directory
    #   shell: bash
    #   working-directory: ${{ inputs.install-output-dir }}
    #   run: tar cf artifact.tar .

    # - name: Upload Install Folder
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: install-artifacts
    #     path: ${{ inputs.install-output-dir }}/artifact.tar

    # - name: Remove tar archive
    #   shell: bash
    #   run: rm -f ${{ inputs.install-output-dir }}/artifact.tar

    # - name: Archive Build Directory
    #   shell: bash
    #   working-directory: ${{ inputs.build-output-dir }}
    #   run: tar cf artifact.tar .

    # - name: Upload Build Folder
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: build-artifacts
    #     path: ${{ inputs.build-output-dir }}/artifact.tar

    # - name: Remove tar archive
    #   shell: bash
    #   run: rm -f ${{ inputs.build-output-dir }}/artifact.tar
