name: "Build tt-xla"
description: "Composite action for building, testing, and uploading artifacts for tt-xla."
inputs:
  build-output-dir:
    description: "Build folder location"
    required: true
  work-dir:
    description: "tt-xla root"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: bash
      run: |
        source venv/activate
        cmake -G Ninja \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DCODE_COVERAGE=ON \
        -B ${{ inputs.build-output-dir }} \
        -S ${{ inputs.work-dir }}

    - name: Build
      shell: bash
      run: |
        source venv/activate
        cmake --build ${{ inputs.build-output-dir }}

    - name: Build the wheel
      shell: bash
      run: |
        source venv/activate
        cd ${{ inputs.work-dir }}/python_package
        python setup.py bdist_wheel

    - name: Upload the wheel
      uses: actions/upload-artifact@v4
      with:
        name: xla-whl-codecov
        path: ${{ inputs.work-dir }}/python_package/dist/pjrt_plugin_tt*.whl

    - name: Archive Build Directory
      shell: bash
      working-directory: ${{ inputs.build-output-dir }}
      run: tar cf artifact.tar .

    - name: Upload Build Folder
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ${{ inputs.build-output-dir }}/artifact.tar

    - name: Remove tar archive
      shell: bash
      run: rm -f ${{ inputs.build-output-dir }}/artifact.tar
