# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

"""Build a text prompt of a target chat-templated token length.

Lifted from ``diffusiongemma_vision_logs/probes/probe_len.py:77-99`` so the
Chisel test, the MoE-block test and the per-layer probe all build the *same*
prompt for a given target -- the generation is deterministic, so the 277-token
prompt reproduces exactly across runs and across tools.

The length is measured AFTER the chat template is applied (``_apply_chat_template``,
loader.py:192), so the target includes template tokens.
"""

import torch

# Deterministic seed sentence -- keep byte-identical to probe_len.py so the
# prompts generated by either path are the same string.
_SEED = (
    "The sky appears blue because molecules in the air scatter blue "
    "light from the sun more than they scatter red light. "
)


def build_prompt(loader, target_tokens, dtype_override=torch.bfloat16):
    """Return ``(prompt, n_tokens)`` for a prompt of ~``target_tokens`` length.

    Grows by whole copies of the seed sentence until the templated length reaches
    the target, then trims word-by-word to land as close to it as possible.
    Re-tokenizes per step, but runs no model forward, so it is cheap.

    Raises if the achieved length is not within 8 tokens of the target -- an
    unnoticed length mismatch would silently invalidate a length-matched
    comparison, which is the whole point of this helper.
    """
    if not target_tokens:
        raise ValueError("target_tokens must be non-zero; caller should skip instead")

    def n_tokens(p):
        return loader.load_text_inputs(dtype_override=dtype_override, prompt=p)[
            "input_ids"
        ].shape[-1]

    words, prompt, trial = _SEED.split(), "", _SEED.strip()
    while True:
        trial = (prompt + " " + " ".join(words)).strip()
        if n_tokens(trial) >= target_tokens:
            break
        prompt = trial

    w = trial.split()
    while len(w) > 1 and n_tokens(" ".join(w)) > target_tokens:
        w = w[:-1]

    prompt = " ".join(w)
    got = n_tokens(prompt)
    # load_text_inputs does `prompt or self.sample_text` (loader.py:232), so an
    # empty prompt would silently revert to the 15-token default.
    assert prompt, "built an empty prompt; it would fall back to sample_text"
    assert (
        abs(got - target_tokens) <= 8
    ), f"length control failed: wanted ~{target_tokens}, got {got}"
    return prompt, got
