# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
"""
InstantMesh model loader implementation for image-to-3D generation.

InstantMesh is a feed-forward framework that generates 3D meshes from a single
image. It uses a TriplaneTransformer backbone with a DINO ViT-B/16 encoder to
produce triplane features from 6 sparse views generated by Zero123++.

Requires the InstantMesh repository to be cloned at /tmp/instant_mesh_repo.

Available variants:
- LARGE: instant_mesh_large checkpoint (FlexiCubes-based mesh output)
"""

import os
import sys
import types
from typing import Optional

import torch
from huggingface_hub import hf_hub_download
from omegaconf import OmegaConf

from ...base import ForgeModel
from ...config import (
    Framework,
    ModelConfig,
    ModelGroup,
    ModelInfo,
    ModelSource,
    ModelTask,
    StrEnum,
)

REPO_ID = "TencentARC/InstantMesh"
INSTANT_MESH_REPO_PATH = "/tmp/instant_mesh_repo"


def _ensure_instantmesh_importable():
    """Ensure the InstantMesh repo is cloned and importable."""
    if "src" not in sys.modules or not hasattr(
        sys.modules.get("src", None), "__path__"
    ):
        if not os.path.isdir(INSTANT_MESH_REPO_PATH):
            import subprocess

            subprocess.check_call(
                [
                    "git",
                    "clone",
                    "--filter=blob:none",
                    "https://github.com/TencentARC/InstantMesh.git",
                    INSTANT_MESH_REPO_PATH,
                ]
            )

        if INSTANT_MESH_REPO_PATH not in sys.path:
            sys.path.insert(0, INSTANT_MESH_REPO_PATH)

        src_mod = types.ModuleType("src")
        sys.modules["src"] = src_mod
        src_mod.__path__ = [os.path.join(INSTANT_MESH_REPO_PATH, "src")]


class ModelVariant(StrEnum):
    """Available InstantMesh model variants."""

    LARGE = "Large"


class ModelLoader(ForgeModel):
    """InstantMesh model loader for the triplane reconstruction backbone."""

    _VARIANTS = {
        ModelVariant.LARGE: ModelConfig(
            pretrained_model_name=REPO_ID,
        ),
    }

    DEFAULT_VARIANT = ModelVariant.LARGE

    # Architecture constants for the large model
    _NUM_INPUT_VIEWS = 6
    _IMAGE_SIZE = 320
    _RENDER_SIZE = 384

    def __init__(self, variant: Optional[ModelVariant] = None):
        super().__init__(variant)

    @classmethod
    def _get_model_info(cls, variant: Optional[ModelVariant] = None) -> ModelInfo:
        if variant is None:
            variant = cls.DEFAULT_VARIANT
        return ModelInfo(
            model="InstantMesh",
            variant=variant,
            group=ModelGroup.VULCAN,
            task=ModelTask.CONDITIONAL_GENERATION,
            source=ModelSource.HUGGING_FACE,
            framework=Framework.TORCH,
        )

    def load_model(self, *, dtype_override=None, **kwargs):
        """Load and return the InstantMesh reconstruction model.

        Returns:
            torch.nn.Module: The InstantMesh triplane reconstruction model.
        """
        _ensure_instantmesh_importable()
        from src.models.lrm_mesh import InstantMesh

        config_path = hf_hub_download(REPO_ID, "configs/instant-mesh-large.yaml")
        config = OmegaConf.load(config_path)

        # Config uses Lightning instantiate_from_config pattern with
        # target/params keys; extract the params dict for direct construction.
        model_params = OmegaConf.to_container(
            config.model_config.get("params", config.model_config),
            resolve=True,
        )
        model_params.pop("target", None)
        model = InstantMesh(**model_params)

        ckpt_path = hf_hub_download(REPO_ID, "ckpts/instant_mesh_large.ckpt")
        state_dict = torch.load(ckpt_path, map_location="cpu", weights_only=False)

        # Checkpoint wraps weights under 'lrm_generator.' prefix
        if "state_dict" in state_dict:
            state_dict = state_dict["state_dict"]
        state_dict = {
            k.replace("lrm_generator.", ""): v
            for k, v in state_dict.items()
            if k.startswith("lrm_generator.")
        }

        model.load_state_dict(state_dict, strict=True)
        model.init_flexicubes_geometry("cpu", fovy=30.0)
        model.eval()

        if dtype_override is not None:
            model = model.to(dtype_override)

        return model

    def load_inputs(self, dtype_override=None, batch_size=1, **kwargs):
        """Load sample inputs for the InstantMesh reconstruction model.

        Returns:
            dict: Input tensors for the model forward pass.
        """
        dtype = dtype_override or torch.float32

        # images: 6 sparse views [B, N_views, C, H, W]
        images = torch.randn(
            batch_size,
            self._NUM_INPUT_VIEWS,
            3,
            self._IMAGE_SIZE,
            self._IMAGE_SIZE,
            dtype=dtype,
        )

        # cameras: camera parameters for each input view [B, N_views, 16]
        # (4x4 extrinsic matrix flattened)
        cameras = torch.randn(
            batch_size,
            self._NUM_INPUT_VIEWS,
            16,
            dtype=dtype,
        )

        # render_cameras: target camera for rendering [B, 1, 16]
        render_cameras = torch.randn(
            batch_size,
            1,
            16,
            dtype=dtype,
        )

        return {
            "images": images,
            "cameras": cameras,
            "render_cameras": render_cameras,
            "render_size": self._RENDER_SIZE,
        }
