name: pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: enarx/spdx@master
        with:
          licenses: Apache-2.0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Run pre-commit
        uses: andrewaylett/pre-commit-action@v4
