name: Generate Forge Models Matrix (call)

on:
  workflow_call:
    inputs:
      test_group_cnt:
        description: 'Test group count for splitting forge models tests'
        required: false
        default: '5'
        type: string
    outputs:
      test-forge-models-matrix:
        description: 'JSON matrix for forge models tests'
        value: ${{ jobs.generate.outputs.test-forge-models-matrix }}

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      test-forge-models-matrix: ${{ steps.generate-forge-models-matrix.outputs.test-forge-models-matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
      - name: Generate tt-forge-models matrix
        id: generate-forge-models-matrix
        shell: bash
        env:
          TEST_GROUP_CNT: ${{ inputs.test_group_cnt }}
        run: |
            SCRIPT_PATH=".github/scripts/generate_test_model_matrix.py"
            TEST_MATRIX_PATH=".github/workflows/test-forge-models-matrix.json"
            TESTS_TO_PARALLELIZE='[
              {
                "runs-on": "n150",
                "name": "run_forge_models_torch"
              },
              {
                "runs-on": "p150",
                "name": "run_forge_models_torch"
              }
            ]'
            python $SCRIPT_PATH $TEST_MATRIX_PATH "$TESTS_TO_PARALLELIZE" $TEST_GROUP_CNT  > modified-matrix.json
            echo "test-forge-models-matrix=$(cat modified-matrix.json | jq -c)" >> $GITHUB_OUTPUT
