name: Run Test Single

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  id-token: write
  packages: write
  checks: write

jobs:
  build-image:
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit
    with:
      dockbuild: all

  build-ttxla:
    uses: ./.github/workflows/call-build.yml
    name: "Build tt-xla"
    secrets: inherit
    needs: build-image
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}
      docker_image_manylinux: ${{ needs.build-image.outputs.docker-image-manylinux }}
      build_types: release,manylinux

  perf-benchmark:
    uses: ./.github/workflows/call-filtered-perf-tests.yml
    needs: [ build-image, build-ttxla ]
    secrets: inherit
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image-base }}
      sh-runner: false
      skip-device-perf: false
      perf_regression_check: true
      adv_filter: '[ {"accuracy-testing": false}, {"runs-on": "n150"}, {"runs-on": "n300-llmbox"}, {"runs-on": "galaxy-wh-6u"} ]'
      artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
      artifact_suffix: ${{ needs.build-ttxla.outputs.artifact_suffix }}
      wheel_build: manylinux
