name: Run Test Single

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        type: string
        required: true
        default: 0.1.0.dev1003
      xla_sha_override:
        description: 'Git SHA of commit in tenstorrent/tt-xla or branch name'
        required: false
        type: string
        default: 81a61e01c2f6f48dc45bc2bb686b90a0cb1bbd0a

permissions:
  contents: write
  actions: read
  id-token: write
  packages: write

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.TT_XLA_RELEASER }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Create and push tag if missing
        shell: bash
        run: |
          set -o pipefail
          tag="${{ inputs.release_tag }}"
          commit="${{ inputs.xla_sha_override }}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git ls-remote --tags origin "refs/tags/$tag" | grep -q "$tag"; then
            echo "Remote tag $tag already exists"
          elif git rev-parse "refs/tags/$tag" >/dev/null 2>&1; then
            echo "Tag $tag already exists"
          else
            git tag -a "$tag" -m "Release $tag" "$commit"
            git push origin "refs/tags/$tag"
          fi
