name: Manual manylinux release tests

on:
  workflow_dispatch:

permissions:
  actions: write
  id-token: write
  packages: write
  checks: write
  contents: write

jobs:
  build-image:
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit

  build-xla-torch:
    runs-on: tt-ubuntu-2204-large-stable
    container:
      image: ${{ vars.HARBOR_PREFIX }}${{ needs.build-image.outputs.docker-image }}
    steps:
      - name: Fix workspace permissions issue
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build xla-torch
        shell: bash
        run: scripts/build_torch_xla.sh

      - name: List built wheel files
        run: find temp -name "*.whl" -type f

      - name: Upload xla-torch wheel
        uses: actions/upload-artifact@v6
        with:
          name: xla-torch-wheel
          path: temp/*.whl
