name: Run Test

# This workflow allows manual triggering of tests with customizable presets, hardware targets, and directories.
# It builds the Docker image and project, sets up test parameters, and runs tests using the specified configuration.

on:
  workflow_dispatch:

permissions:
  actions: write
  packages: write
  checks: write
  contents: read

run-name: 'Test ( Suite: nsumrak/explorer )'

env:
  GH_TOKEN: ${{ github.token }} # for gh cli tool
  TTMLIR_TOOLCHAIN_DIR: /opt/ttmlir-toolchain # We don't actually need this, venv/activate expects this to be set
  TT_XLA_CI: 1

jobs:
  build-image:
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit
    with:
      dockbuild: 'ci'

  build-ttxla:
    needs: build-image
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}
      docker_image_manylinux: ${{ needs.build-image.outputs.docker-image-manylinux }}
      build_types: 'explorer'

  test:
    if: always() && !cancelled() && !failure()
    needs: [ build-image, build-ttxla ]
    runs-on: n150
    container:
      image: ${{ needs.build-image.outputs.docker-image }}
      options: --device /dev/tenstorrent
      volumes:
        - /dev/hugepages:/dev/hugepages
        - /dev/hugepages-1G:/dev/hugepages-1G
        - /etc/udev/rules.d:/etc/udev/rules.d
        - /lib/modules:/lib/modules
        - /opt/tt_metal_infra/provisioning/provisioning_env:/opt/tt_metal_infra/provisioning/provisioning_env
        - /mnt/dockercache:/mnt/dockercache
    steps:
    - name: Mark repo as safe for git
      run: |
        git config --global --add safe.directory /__w/tt-xla/tt-xla
        git config --global --add safe.directory /__w/tt-xla/tt-xla/third_party/tt_forge_models

    - name: Log disk space
      run: df -h

    - name: Set caching env variables
      shell: bash
      run: |
        shared_runners=${{ matrix.build.shared-runners }}
        if [[ "$shared_runners" == "" || "$shared_runners" == "false" ]]; then
          echo "DOCKER_CACHE_ROOT=/mnt/dockercache" >> $GITHUB_ENV
        else
          echo "IRD_LF_CACHE=${{ vars.IRD_LF_CACHE }}" >> $GITHUB_ENV
        fi

    - uses: actions/checkout@v6
      with:
        submodules: recursive
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          .github/scripts/
          .gitmodules
          .test_durations
          pytest.ini
          python_package/requirements.txt
          integrations/vllm_plugin/requirements-vllm-plugin.txt
          tests/

    - name: Download wheel artifact
      uses: actions/download-artifact@v8
      with:
        name: xla-whl-release${{ needs.build-ttxla.outputs.artifact_suffix }}
        path: wheels
        run-id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
        github-token: ${{ github.token }}

    - name: Install wheel
      shell: bash
      run: |
        echo "Downloaded wheel files:"
        ls -la wheels

        source venv/activate
        echo "=== Installing wheel ==="
        pip install wheels/*.whl


    - name: Run Tests
      shell: bash
      run: |
        source venv/activate
        python tests/op_by_op/test_tool_capability.py
