name: Manual manylinux release tests

on:
  workflow_dispatch:

permissions:
  actions: write
  id-token: write
  packages: write
  checks: write
  contents: write

jobs:
  build-image:
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit
    with:
      dockbuild: all

  build-ttxla:
    uses: ./.github/workflows/call-build-manylinux.yml
    name: "Build manylinux tt-xla"
    secrets: inherit
    needs: build-image
    with:
      docker-image: ${{ needs.build-image.outputs.docker-image-manylinux }}

  test-distro:
    needs: build-ttxla
    strategy:
      matrix:
        distro: [ "ubuntu", "suse", "fedora" ]
    name: "Test manylinux wheel on ${{ matrix.distro }}"
    uses: ./.github/workflows/call-test-manylinux-distro.yml
    secrets: inherit
    with:
      distro: ${{ matrix.distro }}
