name: Performance Benchmark

on:
  workflow_dispatch:
    inputs:
      mlir_override:
        description: 'Git SHA of commit in tenstorrent/tt-mlir'
        required: false
        type: string
      same_branch:
        description: 'Run on the branch with same name in tt-forge as the current workflow'
        required: false
        type: boolean
      tt_forge_branch:
        description: 'Branch of tt-forge to run the benchmarks on (empty=main)'
        required: false
        type: string
      test_filter:
        description: "Only run tests with name that contains"
        required: false
        type: string

permissions:
  packages: write
  checks: write
  contents: write

jobs:
  docker-build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      mlir_override: ${{ inputs.mlir_override }}
  build:
    needs: docker-build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      mlir_override: ${{ inputs.mlir_override }}
      docker_image: ${{ needs.docker-build.outputs.docker-image }}
  set-inputs:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-inputs.outputs.ref }}
    steps:
      - id: set-inputs
        run: |
          if [ "${{ inputs.same_branch }}" == 'true' ]; then
            echo "ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            if [ -z "${{ inputs.tt_forge_branch }}" ]; then
              echo "ref=main" >> $GITHUB_OUTPUT
            else
              echo "ref=${{ inputs.tt_forge_branch }}" >> $GITHUB_OUTPUT
            fi
          fi
  perf-benchmark:
    needs: set-inputs
    uses: tenstorrent/tt-forge/.github/workflows/perf-benchmark.yml@main
    secrets: inherit
    with:
        project: tt-xla
        run_id: ${{ github.run_id }}
        run_id_source: tt-xla
        ref: ${{ needs.set-inputs.outputs.ref }}
        test-filter: ${{ inputs.test_filter }}
