name: On PR

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  checks: write
  pull-requests: write
  id-token: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/call-pre-commit.yml
    secrets: inherit

  inspect-changes:
    uses: ./.github/workflows/call-inspect-changes.yml
    secrets: inherit

  build-image:
    needs: [ inspect-changes ]
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit
    with:
      dockbuild: ${{ needs.inspect-changes.outputs.wheel-changes == 'true' && 'all' || 'ci' }}

  build-ttxla:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-build.yml
    name: "Build tt-xla"
    secrets: inherit
    needs: [ inspect-changes, build-image ]
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}
      docker_image_manylinux: ${{ needs.build-image.outputs.docker-image-manylinux }}
      build_types: ${{ needs.inspect-changes.outputs.wheel-changes == 'true' && 'release,explorer,manylinux' || 'release,explorer' }}
      needs_build: ${{ needs.inspect-changes.outputs.needs-build }}

  build-ttxla-debug:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false' && needs.inspect-changes.outputs.needs-build != 'false'
    uses: ./.github/workflows/call-build-debug.yml
    name: "Build and test tt-xla (debug with coverage)"
    secrets: inherit
    needs: [ inspect-changes, build-image ]
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}

  test:
    needs: [ inspect-changes, build-image, build-ttxla ]
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false' && needs.inspect-changes.outputs.only-run-forge-models != 'true'
    uses: ./.github/workflows/call-test.yml
    secrets: inherit
    with:
      test_suite: basic-test.json
      docker_image: ${{ needs.build-image.outputs.docker-image-base }}
      artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
      artifact_suffix: ${{ needs.build-ttxla.outputs.artifact_suffix }}

  perf-benchmark:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false' && needs.inspect-changes.outputs.only-run-forge-models != 'true' && vars.RUN_PERF_ON_UPLIFT == 'true' && github.event_name == 'pull_request' && (contains(needs.inspect-changes.outputs.detected-uplifts, 'tt-mlir') || contains(needs.inspect-changes.outputs.detected-uplifts, 'transformers'))
    needs: [ inspect-changes, build-image, build-ttxla ]
    uses: ./.github/workflows/call-filtered-perf-tests.yml
    secrets: inherit
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image-base }}
      adv_filter: '[
        { "accuracy-testing": false },
        { "runs-on": "n150", "filter": ["resnet","llama_3_1_8b_instruct","qwen_3_4b_embedding"] },
        { "runs-on": "n300-llmbox", "filter": ["llama_3_1_70b_tp", "gpt_oss_20b_tp"] },
        { "runs-on": "galaxy-wh-6u", "filter": ["llama_3_1_70b_tp_galaxy"] } ]'
      sh-runner: false
      skip-device-perf: true
      perf_regression_check: false
      artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
      artifact_suffix: ${{ needs.build-ttxla.outputs.artifact_suffix }}

  test_forge_models_push:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-test.yml
    secrets: inherit
    needs: [ inspect-changes, build-image, build-ttxla ]
    with:
      test_suite: model-test-push.json
      docker_image: ${{ needs.build-image.outputs.docker-image }}
      artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
      artifact_suffix: ${{ needs.build-ttxla.outputs.artifact_suffix }}

  test-uplift-extended:
    if: needs.inspect-changes.outputs.detected-uplifts != ''
    uses: ./.github/workflows/call-test.yml
    secrets: inherit
    needs: [ inspect-changes, build-image, build-ttxla ]
    with:
      test_suite: ${{ needs.inspect-changes.outputs.uplift-additional-test-suites }}
      docker_image: ${{ needs.build-image.outputs.docker-image }}
      artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
      artifact_suffix: ${{ needs.build-ttxla.outputs.artifact_suffix }}

  test-tools:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-test-tools.yml
    secrets: inherit
    needs: [ inspect-changes, build-image, build-ttxla ]
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}
      wheel_artifact_name: xla-whl-release${{ needs.build-ttxla.outputs.artifact_suffix }}
      artifacts_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}

  build-docs:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    needs: [ inspect-changes, build-image, build-ttxla ]
    uses: ./.github/workflows/call-check-docs-build.yml
    secrets: inherit
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}

  check-all-green:
    if: always()
    needs:
      - pre-commit
      - inspect-changes
      - build-image
      - build-ttxla
      - build-ttxla-debug
      - test
      - test_forge_models_push
      - test-uplift-extended
      - test-tools
      - perf-benchmark
      - build-docs
    runs-on: Ubuntu-latest
    steps:
    - name: Check if the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: build-image, build-ttxla, build-ttxla-debug, test, test_forge_models_push, test-uplift-extended, test-tools, perf-benchmark, build-docs
        jobs: ${{ toJSON(needs) }}
