name: On PR

on:
  push:

permissions:
  contents: write
  packages: write
  checks: write
  pull-requests: write
  id-token: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  inspect-changes:
    runs-on: ubuntu-latest
    outputs:
      skip-build-and-test: ${{ steps.inspect.outputs.skip-build-and-test }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/inspect-changes
        id: inspect

  build-image:
    needs: [ inspect-changes ]
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit

  build-ttxla-release:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-build.yml
    name: "Build tt-xla release"
    secrets: inherit
    needs: [ inspect-changes, build-image ]
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}

  perf-benchmark-n150:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    needs: [ inspect-changes, build-image, build-ttxla-release ]
    uses: ./.github/workflows/manual-benchmark.yml
    secrets: inherit
    with:
      docker_image: 'ghcr.io/tenstorrent/tt-xla-slim:161b6f42f1e3fea9acc03793035023035e624734'
      runs-on-filter: n150
      sh-runner: false
      skip-device-perf: true
      perf_regression_check: false
      test_filter: resnet,llama_3_1_8b_instruct,qwen_3_4b_embedding
      should_build_wheel: false
      artifact_release_run_id: ${{ needs.build-ttxla-release.outputs.artifacts_run_id }}
      wheel_release_artifact_name: ${{ needs.build-ttxla-release.outputs.wheel_artifact_name }}

  perf-benchmark-llmbox:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    needs: [ inspect-changes, build-image, build-ttxla-release ]
    uses: ./.github/workflows/manual-benchmark.yml
    secrets: inherit
    with:
      docker_image: 'ghcr.io/tenstorrent/tt-xla-slim:161b6f42f1e3fea9acc03793035023035e624734'
      runs-on-filter: n300-llmbox
      sh-runner: false
      skip-device-perf: true
      perf_regression_check: false
      test_filter: test_llama_3_1_70b_tp
      should_build_wheel: false
      artifact_release_run_id: ${{ needs.build-ttxla-release.outputs.artifacts_run_id }}
      wheel_release_artifact_name: ${{ needs.build-ttxla-release.outputs.wheel_artifact_name }}

  check-all-green:
    if: always()
    needs:
      - build-image
      - build-ttxla-release
      - perf-benchmark-n150
      - perf-benchmark-llmbox
    runs-on: Ubuntu-latest
    steps:
    - name: Check if the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: build-image, build-ttxla-release, perf-benchmark-n150, perf-benchmark-llmbox
        jobs: ${{ toJSON(needs) }}
