name: Performance benchmark experimental

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  actions: write
  packages: write
  checks: write
  contents: write

jobs:
  build-image:
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit

  build-ttxla:
    uses: ./.github/workflows/call-build.yml
    name: "Build tt-xla"
    secrets: inherit
    needs: build-image
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}

  run-accuracy-benchmarks:
    needs: [build-image, build-ttxla]
    secrets: inherit
    uses: ./.github/workflows/call-test.yml
    with:
      test_suite: perf-accuracy.json
      docker_image: ${{ needs.build-image.outputs.docker-image-base }}
      artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
      artifact_suffix: ${{ needs.build-ttxla.outputs.artifact_suffix }}

  perf-regression-check:
    needs: [run-accuracy-benchmarks]
    if: success() || failure()
    secrets: inherit
    uses: ./.github/workflows/call-perf-regression-check.yml
    with:
      mode: accuracy

  fail-notify:
    needs:
      - run-accuracy-benchmarks
      - perf-regression-check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check if the needed jobs succeeded or failed
        id: check
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
