name: Build tt-xla Wheel

on:
  workflow_dispatch:
    inputs:
      docker-tag:
        description: 'Docker tag for the manylinux image'
        required: false
        type: string
        default: 'latest'
  workflow_call:
    inputs:
      docker-tag:
        description: 'Docker tag for the manylinux image'
        required: false
        type: string
        default: 'latest'

jobs:
  build-ttxla-wheel:
    timeout-minutes: 60
    name: Build tt-xla Python Wheel
    runs-on: ubuntu-latest

    steps:
      - name: Maximize space
        uses: tenstorrent/tt-github-actions/.github/actions/maximize_space@main

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
          echo "build-output-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"
          echo "wheel-output-dir=$(pwd)/dist" >> "$GITHUB_OUTPUT"

      - name: Git safe dir
        run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build tt-xla Wheel (manylinux)
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_ENVIRONMENT: "IN_CIBW_ENV=ON"
          CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/tenstorrent/tt-xla/tt-xla-manylinux-2-34:${{ inputs.docker-tag || 'latest' }}
        with:
          output-dir: ${{ steps.strings.outputs.wheel-output-dir }}
          package-dir: ${{ steps.strings.outputs.work-dir }}
          config-file: "${{ steps.strings.outputs.work-dir }}/python_package/pyproject.toml"

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: ttxla-wheel
          path: ${{ steps.strings.outputs.wheel-output-dir }}/*.whl
          if-no-files-found: error

  test-ttxla-wheel-install:
    needs: build-ttxla-wheel
    timeout-minutes: 30
    name: Test ttxla Wheel Installation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git safe dir
        run: git config --global --add safe.directory $(pwd)

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: ttxla-wheel
          path: ./dist

      - name: Test wheel installation
        shell: bash
        run: |
          WHEEL_FILE=$(ls ./dist/*.whl)
          echo "Installing wheel: $WHEEL_FILE"
          pip install $WHEEL_FILE

          # Test the installation
          python -c "from ttmlir import ir; print('Imported ttmlir & Created CTX: ', ir.Context())"
